test:
  script:
    - echo "Testando o Runner..."
    - ls -la

deploy_dev:
  script:
    - cd /var/www/gitlab/Pindamonhangaba.Observability
    - git pull https://almoreira:glpat-G4ppSEYRAkPD4zQ7j4GE@gitlab.com/setip-dsi/Pindamonhangaba.Observability.git
    - pip install -r requirements.txt
    - python3 main.py